services:
  # ===========================================================================
  # DATABASE - POSTGRESQL
  # ===========================================================================
  postgres:
    image: postgres:15-alpine
    container_name: tibia-tracker-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Removido ports para bloquear acesso externo - apenas acesso interno via Docker network
    networks:
      - tibia-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===========================================================================
  # CACHE - REDIS
  # ===========================================================================
  redis:
    image: redis:7-alpine
    container_name: tibia-tracker-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # Removido ports para bloquear acesso externo - apenas acesso interno via Docker network
    volumes:
      - redis_data:/data
    networks:
      - tibia-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===========================================================================
  # BACKEND API - FASTAPI
  # ===========================================================================
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: tibia-tracker-backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USER_AGENT=${USER_AGENT}
      - SCRAPE_DELAY_SECONDS=${SCRAPE_DELAY_SECONDS}
      - SCRAPE_TIMEOUT_SECONDS=${SCRAPE_TIMEOUT_SECONDS}
      - TALEON_SAN_URL=${TALEON_SAN_URL}
      - TALEON_AURA_URL=${TALEON_AURA_URL}
      - TALEON_GAIA_URL=${TALEON_GAIA_URL}
    # Removido ports para bloquear acesso externo - apenas acesso interno via Docker network
    volumes:
      - ./Backend:/app
      - backend_logs:/var/log/tibia-tracker
      - outfits_data:/app/outfits
    networks:
      - tibia-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===========================================================================
  # FRONTEND - REACT
  # ===========================================================================
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT}
    container_name: tibia-tracker-frontend
    ports:
      - "3000:80"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - tibia-network
    depends_on:
      - backend
    restart: unless-stopped

  # ===========================================================================
  # PROXY REVERSO - CADDY
  # ===========================================================================
  caddy:
    image: caddy:2-alpine
    container_name: tibia-tracker-caddy
    ports:
      - "${CADDY_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
    volumes:
      - ./Scripts/Deploy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - tibia-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - SSL_EMAIL=${SSL_EMAIL}

  # ===========================================================================
  # MONITORAMENTO - PROMETHEUS
  # ===========================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: tibia-tracker-prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./Scripts/Deploy/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - tibia-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  # ===========================================================================
  # NODE EXPORTER
  # ===========================================================================
  node-exporter:
    image: prom/node-exporter:latest
    container_name: tibia-tracker-node-exporter
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - tibia-network
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_logs:
    driver: local
  outfits_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  prometheus_data:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  tibia-network:
    driver: bridge 