# =============================================================================
# TIBIA TRACKER - CONFIGURAÇÃO PROMETHEUS
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (métricas do sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Backend API
  - job_name: 'tibia-tracker-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Frontend (via Nginx)
  - job_name: 'tibia-tracker-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # PostgreSQL monitoring (if pg_exporter is added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:5432']

  # Redis monitoring (if redis_exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379'] 